channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
dependencies:
  - python==3.10
  - pytorch::pytorch
  - pytorch::pytorch-cuda==12.4
  - nvidia::cuda-toolkit==12.4
  - numpy
  - scipy
  - seaborn
  - h5py 
  - hdbscan 
  - gcc 
  - openmp 
  - tqdm 
  - biopython 
  - fraggenescan 
  - hmmer 
  - tabulate